- clean: ['~']

- link:
    ~/.profile:
      force: true
      path: profile
    ~/.bashrc:
      force: true
      path: bashrc
    ~/.ssh/config:
      create: true
      path: ssh/config
    ~/.ssh/config.d:
      path: private/ssh/config.d
      ignore-missing: true
    ~/.gitconfig: gitconfig
    ~/.config/Code/User/settings.json: vscode/settings.json
    ~/.config/MangoHud: MangoHud
    ~/.pyenv: pyenv
    ~/.phpenv: phpenv
    ~/.phpenv/plugins/php-build:
        create: true
        path: php-build
    ~/.nvm: nvm

- vscode:
  - "AndrsDC.base16-themes"
  - 'fkrull.gtk-dark-titlebar'
  - "EditorConfig.EditorConfig"
  - "drewbarrett.vscode-coffeescript-preview"
  - "xdebug.php-debug"
  - "bmewburn.vscode-intelephense-client"
  - "humao.rest-client"
  - "icrawl.discord-vscode"
  - "kleber-swf.ocean-dark-extended"
  - "mikestead.dotenv"
  - "ms-python.python"
  - "ms-dotnettools.csharp"
  - "ms-azuretools.vscode-docker"
  - "vscode-icons-team.vscode-icons"
  - "vscjava.vscode-java-pack"
  - "vscodevim.vim"
  - "phil294.coffeesense"
  - "junstyle.php-cs-fixer"
  - "MS-vsliveshare.vsliveshare-pack"
  - "james-yu.latex-workshop"
  - "tecosaur.latex-utilities"
  - "onecentlin.laravel-blade"
  - "codingyu.laravel-goto-view"
  - "octref.vetur"
  - "zignd.html-css-class-completion"
  - "ms-vscode.cpptools-extension-pack"
  - "ms-python.vscode-pylance"
  - "dart-code.dart-code"
  - "dart-code.flutter"
  - "zxh404.vscode-proto3"
  - "robert-brunhage.flutter-riverpod-snippets"
  - "eamodio.gitlens"
  - "firefox-devtools.vscode-firefox-debug"
  - "ms-vscode-remote.vscode-remote-extensionpack"
  - "cschlosser.doxdocgen"
  - "editorconfig.editorconfig"
  - "visualstudioexptteam.vscodeintellicode"
  - "dotjoshjohnson.xml"
  - "redhat.vscode-yaml"
  - "rust-lang.rust-analyzer"

- shell:
    - [dconf load / < dconf, Applying GNOME settings]
    - [chmod 700 ~/.ssh && chmod 600 ~/.ssh/config && chmod 700 ~/.ssh/config.d && chmod 600 ~/.ssh/config.d/*, Setting SSH config permissions]
    - [git submodule sync --recursive, Installing submodules]
