- clean: ['~']

- link:
    ~/.profile:
      force: true
      path: profile
    ~/.bashrc:
      force: true
      path: bashrc
    ~/.gitconfig: gitconfig
    ~/.config/Code/User/settings.json: vscode/settings.json
    ~/.config/MangoHud: MangoHud
    ~/.pyenv: pyenv
    ~/.phpenv: phpenv
    ~/.phpenv/plugins/php-build:
        create: true
        path: php-build
    ~/.nvm: nvm

- gsettings:
    - schema: 'org.gnome.desktop.wm.preferences'
      key: 'action-middle-click-titlebar'
      value: "'minimize'"

    - schema: 'org.gnome.desktop.peripherals.mouse'
      key: 'accel-profile'
      value: "'flat'"

    - schema: 'org.gnome.desktop.interface'
      key: 'clock-show-weekday'
      value: 'true'

    - schema: 'org.gnome.desktop.interface'
      key: 'clock-show-seconds'
      value: 'true'

- vscode:
  - "AndrsDC.base16-themes"
  - 'fkrull.gtk-dark-titlebar'
  - "EditorConfig.EditorConfig"
  - "drewbarrett.vscode-coffeescript-preview"
  - "felixfbecker.php-debug"
  - "bmewburn.vscode-intelephense-client"
  - "humao.rest-client"
  - "icrawl.discord-vscode"
  - "kleber-swf.ocean-dark-extended"
  - "mikestead.dotenv"
  - "ms-python.python"
  - "ms-dotnettools.csharp"
  - "ms-vscode.mono-debug"
  - "ms-azuretools.vscode-docker"
  - "redhat.java"
  - "vscode-icons-team.vscode-icons"
  - "vscjava.vscode-java-debug"
  - "vscjava.vscode-java-pack"
  - "vscjava.vscode-java-test"
  - "vscjava.vscode-maven"
  - "vscodevim.vim"
  - "yorkxin.coffeescript-support"
  - "ms-vscode.vscode-typescript-tslint-plugin"
  - "junstyle.php-cs-fixer"
  - "MS-vsliveshare.vsliveshare-pack"
  - "james-yu.latex-workshop"
  - "tecosaur.latex-utilities"
  - "onecentlin.laravel-blade"
  - "codingyu.laravel-goto-view"
  - "octref.vetur"
  - "tht13.html-preview-vscode"
  - "zignd.html-css-class-completion"
  - "ms-vscode.cpptools"
  - "ms-python.vscode-pylance"
  - "dart-code.flutter"
  - "eamodio.gitlens"
  - "golang.go"

- shell:
    - [git submodule sync --recursive, Installing submodules]
