- link:
    ~/.config/Code/User/settings.json: vscode/settings.json
    ~/.config/MangoHud: MangoHud

- vscode:
    - 'fkrull.gtk-dark-titlebar'

- gsettings:
    - schema: 'org.gnome.desktop.wm.preferences'
      key: 'action-middle-click-titlebar'
      value: "'minimize'"
