- link:
    ~/.config/Code/User/settings.json: vscode/settings.json
    ~/.config/MangoHud: MangoHud

- vscode:
    - 'fkrull.gtk-dark-titlebar'

- gsettings:
    - schema: 'org.gnome.desktop.wm.preferences'
      key: 'action-middle-click-titlebar'
      value: "'minimize'"

    - schema: 'org.gnome.desktop.peripherals.mouse'
      key: 'accel-profile'
      value: "'flat'"

    - schema: 'org.gnome.desktop.interface'
      key: 'clock-show-weekday'
      value: 'true'

    - schema: 'org.gnome.desktop.interface'
      key: 'clock-show-seconds'
      value: 'true'
